// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:0d4853c7-f0ad-4ebb-b91c-504c0dbbdad4",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_z2pQXSoaz",
  aws_user_pools_web_client_id: "iusugjeelfagude9pnutiruhj",
  aws_appsync_graphqlEndpoint:
    "https://xuficmeo2rci7inbjp6h5izxzi.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS"
};

export default awsmobile;
